### ISSUE TITLE
is it safe? what are chances of getting blockeor shadow banned ?

### ISSUE THREAD

**Issue by ishandutta2007** [ougrocks/instagram-post-scheduler#1]

**Comment by rdxshubham** [comment]
Yes it is safe, hence it is using the internal Instagram mobile apis.

**Comment by ishandutta2007** [comment]
@ougrocks Let me explain where I am coming from. Let me explain my scenario in detail.
I have been using scheduling via schedulers like hootsuite or buffer which instagram officially supports but the issue with that is very ofter then token expires and I have to keep connecting every couple of days.
The concern I have is, as per my understanding normally it detects device types, app id, iemi etc. Are those being spoofed via this mobile APIs too or else I fear the posts may loose engagement(a sign of decreased trust score) even if they are being allowed to post ?

**Comment by ishandutta2007** [comment]
@ougrocks would be great if you can you share few of your accounts so that I can verify the engagements.
